electrostore/electrostore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("goods/", include("goods.urls", namespace="goods")),
    path("users/", include("users.urls", namespace="users")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electrostore/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

electrostore/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

electrostore/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True)

    def __str__(self) -> str:
        return self.username

electrostore/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm, UserChangeForm
)

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User()
        fields = ("username", "password")


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

class ProfileForm(UserChangeForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
        )

electrostore/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from main.models import Category
from .forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from carts.models import Cart


def login(request):
    categories = Category.objects.all()

    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key
            if user:
                auth.login(request, user)

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserLoginForm()

    context = {"title": "Login", "categories": categories, "form": form}
    return render(request, "users/login.html", context)


def registration(request):
    categories = Category.objects.all()

    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserRegistrationForm()

    context = {"title": "Sign In", "categories": categories, "form": form}
    return render(request, "users/registration.html", context)


@login_required
def profile(request):
    categories = Category.objects.all()

    if request.method == "POST":
        form = ProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        "title": f"Profile - {request.user.username}",
        "categories": categories,
        "form": form,
    }
    return render(request, "users/profile.html", context)


@login_required()
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main:index"))

electrostore/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-7">
          <!-- Login Details -->
          <div class="billing-details">
            <div class="section-title">
              <h3 class="title">LOGIN</h3>
            </div>
            <form action="{% url 'users:login' %}" method="POST">
              {% csrf_token %}
              {% if form.non_field_errors %}
              <div class="alert alert-primary" role="alert">{{ form.non_field_errors }}</div>
              {% endif %}
              <div class="form-group">
                <label for="id_username">Username</label>
                <input class="input" type="text" name="username" id="id_username" placeholder="Enter your username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required />
              </div>
              <div class="form-group">
                <label for="id_password">Password</label>
                <input class="input" type="password" name="password" id="id_password" placeholder="Enter your password" required />
              </div>
              <button type="submit" class="primary-btn order-submit"> LOGIN </button>
            </form>
            <br />
            <a class="primary-btn order-submit" style="background-color: blue;" href="{% url 'users:registration' %}">Sign In</a>
          </div>
          <!-- /Login Details -->
        </div>
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->
{% endblock %}

electrostore/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-7">
          <!-- Login Details -->
          <div class="billing-details">
            <div class="section-title">
              <h3 class="title">Profile</h3>
            </div>
            <form action="{% url 'users:profile' %}" method="POST">
              {% csrf_token %}
              {% if form.non_field_errors %}
                <p>{{ form.non_field_errors }}</p>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="first_name" id="id_first_name" placeholder="First Name" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" required />
              </div>
              {% if form.first_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="last_name" id="id_last_name" placeholder="Last Name" value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" required />
              </div>
              {% if form.last_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="username" id="id_username" placeholder="Username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required />
              </div>
              {% if form.username.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="email" name="email" id="id_email" placeholder="Email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required />
              </div>
              {% if form.email.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
              {% endif %}
              <button type="submit" class="primary-btn order-submit">Change</button>
            </form>
            <br />
          </div>
          <!-- /Login Details -->
        </div>

          <!-- Order Details -->
          <div class="col-md-5 order-details">
            <div class="section-title text-center">
              <h3 class="title">Your Order</h3>
            </div>
            {% include "carts/includes/included_cart.html" %}
          </div>
          </div>
          <!-- /Order Details -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->
  
{% endblock %}

electrostore/users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-7">
          <!-- Login Details -->
          <div class="billing-details">
            <div class="section-title">
              <h3 class="title">SIGN IN</h3>
            </div>
            <form action="{% url 'users:registration' %}" method="POST">
              {% csrf_token %}
              {% if form.non_field_errors %}
                <div class="alert alert-primary" role="alert">{{ form.non_field_errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="first_name" id="id_first_name" placeholder="First Name" required />
              </div>
              {% if form.first_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="last_name" id="id_last_name" placeholder="Last Name" required />
              </div>
              {% if form.last_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="username" id="id_username" placeholder="Username" required />
              </div>
              {% if form.username.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="email" name="email" id="id_email" placeholder="Email" required />
              </div>
              {% if form.email.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="password" name="password1" id="id_password1" placeholder="Password" required />
              </div>
              {% if form.password1.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="password" name="password2" id="id_password2" placeholder="Password Again" required />
              </div>
              {% if form.password2.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
              {% endif %}
              <button type="submit" class="primary-btn order-submit">SIGN IN</button>
            </form>
            <br />
            <a class="primary-btn order-submit" style="background-color: blue;" href="{% url 'users:login' %}">Log in</a>
          </div>
          <!-- /Login Details -->
        </div>
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->
{% endblock %}