electrostore/electrostore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("goods/", include("goods.urls", namespace="goods")),
    path("users/", include("users.urls", namespace="users")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electrostore/goods/urls.py
from django.urls import path
from . import views

app_name = "goods"

urlpatterns = [
    path("search", views.catalog, name="search"),
    path("<slug:product_slug>/", views.product, name="product"),
    path("catalog/<slug:category_slug>/", views.catalog, name="catalog"),
]

electrostore/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

electrostore/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [path("create_order/", views.create_order, name="create_order")]

electrostore/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

electrostore/templates/base.html
{% load static %}
{% load goods_tags %}
{% load cart_tags %}

{% user_carts request as carts %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{{ title }}</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet" />

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>
  <body>
    <!-- HEADER -->
    <header>
      <!-- TOP HEADER -->
      <div id="top-header">
        <div class="container">
          <ul class="header-links pull-left">
            <li>
              <a href="#"><i class="fa fa-phone"></i> +123-45-67-89</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a>
            </li>
          </ul>
          <ul class="header-links pull-right">
            {% if not user.is_authenticated %}
              <li>
                <a href="{% url 'users:login' %}"><i class="fa fa-sign-out"></i> Log In</a>
              </li>
            {% else %}
              <li>
                <a href="{% url 'users:profile' %}"><i class="fa fa-user-o"></i> {{ user.username }}</a>
              </li>
              <li>
                <a href="{% url 'users:logout' %}"><i class="fa fa-sign-out"></i> Log Out</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
      <!-- /TOP HEADER -->

      <!-- MAIN HEADER -->
      <div id="header">
        <!-- container -->
        <div class="container">
          <!-- row -->
          <div class="row">
            <!-- LOGO -->
            <div class="col-md-3">
              <div class="header-logo">
                <a href="{% url 'main:index' %}" class="logo"><img src="{% static './img/logo.png' %}" alt="logo" /></a>
              </div>
            </div>
            <!-- /LOGO -->

            <!-- SEARCH BAR -->
            <div class="col-md-6">
              <div class="header-search">
                <form action="{% url 'goods:search' %}" method="GET">
                  <input class="input" type="search" name="q" placeholder="Search here" />
                  <button class="search-btn">Search</button>
                </form>
              </div>
            </div>
            <!-- /SEARCH BAR -->

            <!-- ACCOUNT -->
            <div class="col-md-3 clearfix">
              <div class="header-ctn">
                <!-- Cart -->
                <div class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                    <i class="fa fa-shopping-cart"></i>
                    <span>Your Cart</span>
                    <div class="qty">{{carts.total_quantity}}</div>
                  </a>
                  <div class="cart-dropdown">
                    {% include 'carts/includes/included_cart.html' %}
                    <div class="cart-btns">
                      <a href="{% url "users:profile" %}">View Cart</a>
                      <a href="{% url "orders:create_order" %}">Checkout <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                  </div>
                </div>
                <!-- /Cart -->

                <!-- Menu Toogle -->
                <div class="menu-toggle">
                  <a href="#">
                    <i class="fa fa-bars"></i>
                    <span>Menu</span>
                  </a>
                </div>
                <!-- /Menu Toogle -->
              </div>
            </div>
            <!-- /ACCOUNT -->
          </div>
          <!-- row -->
        </div>
        <!-- container -->
      </div>
      <!-- /MAIN HEADER -->
    </header>
    <!-- /HEADER -->

    <!-- NAVIGATION -->
    <nav id="navigation">
      <!-- container -->
      <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
          <!-- NAV -->
          <ul class="main-nav nav navbar-nav">
            <li class="active">
              <a href="{% url 'main:index' %}">Home</a>
            </li>
            {% for category in categories %}
              <li>
                <a href="{% url 'goods:catalog' category.slug %}">{{ category.name }}</a>
              </li>
            {% endfor %}
          </ul>
          <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
      </div>
      <!-- /container -->
    </nav>
    <!-- /NAVIGATION -->

    {% block content %}

    {% endblock %}

    <!-- FOOTER -->
    <footer id="footer">
      <!-- top footer -->
      <div class="section">
        <!-- container -->
        <div class="container">
          <!-- row -->
          <div class="row">
            <div class="col-md-3 col-xs-6">
              <div class="footer">
                <h3 class="footer-title">About Us</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
                <ul class="footer-links">
                  <li>
                    <a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a>
                  </li>
                  <li>
                    <a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a>
                  </li>
                  <li>
                    <a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a>
                  </li>
                </ul>
              </div>
            </div>

            <div class="col-md-3 col-xs-6">
              <div class="footer">
                <h3 class="footer-title">Categories</h3>
                <ul class="footer-links">
                  {% for category in categories %}
                    <li>
                      <a href="{% url 'goods:catalog' category.slug %}">{{ category.name }}</a>
                    </li>
                  {% endfor %}
                </ul>
              </div>
            </div>

            <div class="clearfix visible-xs"></div>

            <div class="col-md-3 col-xs-6">
              <div class="footer">
                <h3 class="footer-title">Information</h3>
                <ul class="footer-links">
                  <li>
                    <a href="#">About Us</a>
                  </li>
                  <li>
                    <a href="#">Contact Us</a>
                  </li>
                  <li>
                    <a href="#">Privacy Policy</a>
                  </li>
                  <li>
                    <a href="#">Orders and Returns</a>
                  </li>
                  <li>
                    <a href="#">Terms & Conditions</a>
                  </li>
                </ul>
              </div>
            </div>

            <div class="col-md-3 col-xs-6">
              <div class="footer">
                <h3 class="footer-title">Service</h3>
                <ul class="footer-links">
                  <li>
                    <a href="{% url "users:profile" %}">My Account</a>
                  </li>
                  <li>
                    <a href="{% url "users:profile" %}">View Cart</a>
                  </li>
                  <li>
                    <a href="#">Help</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <!-- /row -->
        </div>
        <!-- /container -->
      </div>
      <!-- /top footer -->

      <!-- bottom footer -->
      <div id="bottom-footer" class="section">
        <div class="container">
          <!-- row -->
          <div class="row">
            <div class="col-md-12 text-center">
              <ul class="footer-payments">
                <li>
                  <a href="#"><i class="fa fa-cc-visa"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-credit-card"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-cc-paypal"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-cc-mastercard"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-cc-discover"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-cc-amex"></i></a>
                </li>
              </ul>
              <span class="copyright">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>
                                  document.write(new Date().getFullYear())
                                </script>All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </span>
            </div>
          </div>
          <!-- /row -->
        </div>
        <!-- /container -->
      </div>
      <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->

    <!-- jQuery Plugins -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/nouislider.min.js' %}"></script>
    <script src="{% static 'js/jquery.zoom.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>