electrostore/electrostore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("goods/", include("goods.urls", namespace="goods")),
    path("users/", include("users.urls", namespace="users")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electrostore/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

electrostore/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [path("create_order/", views.create_order, name="create_order")]

electrostore/orders/models.py
from django.db import models
from users.models import User
from main.models import Product


class OrderitemQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.SET_DEFAULT, default=None, blank=True, null=True
    )
    created_timestamp = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    requires_delivery = models.BooleanField(default=False)
    delivery_address = models.TextField(null=True, blank=True)
    payment_on_get = models.BooleanField(default=False)
    order_notes = models.TextField(null=True, blank=True)
    is_paid = models.BooleanField(default=False)
    status = models.CharField(max_length=50, default="In processing")

    class Meta:
        db_table = "order"

    def __str__(self) -> str:
        return f"Order № {self.pk} | User {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE)
    product = models.ForeignKey(
        to=Product, on_delete=models.SET_DEFAULT, null=True, default=None
    )
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "order_item"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self) -> str:
        return f"Product {self.name} | Order № {self.order.pk}"

electrostore/orders/forms.py
import re
from django import forms

class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", "False"),
            ("1", "True")
        ]
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", "False"),
            ("1", "True")
        ]
    )
    order_notes = forms.CharField(required=False)

    def clean_phone_number(self):
        data = self.cleaned_data["phone_number"]

        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")

        pattern = re.compile(r"^\d{10}$")
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера")

        return data

electrostore/orders/views.py
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render

from carts.models import Cart
from orders.forms import CreateOrderForm
from .models import Order, OrderItem


def create_order(request):
    if request.method == "POST":
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        # create order
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data["phone_number"],
                            email=form.cleaned_data["email"],
                            requires_delivery=form.cleaned_data["requires_delivery"],
                            delivery_address=form.cleaned_data["delivery_address"],
                            payment_on_get=form.cleaned_data["payment_on_get"],
                            order_notes=form.cleaned_data["order_notes"],
                        )

                        # create ordered goods
                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.sell_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(
                                    f"Not enough product {name} quantity\
                                                    In stock - {product.quantity}"
                                )

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        # empty users cart after creating and order
                        cart_items.delete()
                        print("Order is created!")
                        return redirect("users:profile")
            except ValidationError as e:
                print(e)
                return redirect("cart:order")

    else:
        initial = {
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,
        }

        form = CreateOrderForm(initial=initial)

    context = {"title": "Create order", "form": form}

    return render(request, "orders/create_order.html", context=context)

electrostore/orders/templates/orders/create_order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <form action="{% url 'orders:create_order' %}" method="POST">
          <div class="col-md-7">
            <!-- Shipping Details -->

            {% csrf_token %}
            <div class="billing-details">
              <div class="section-title">
                <h3 class="title">Shipping address</h3>
              </div>
              <div class="form-group">
                <input class="input" type="text" name="first_name" placeholder="First Name" id="id_first_name" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" />
              </div>
              {% if form.first_name.errors %}
                <div class="alert alert-danger alert-dismissible">{{ form.first_name.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="last_name" placeholder="Last Name" id="id_last_name" value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" />
              </div>
              {% if form.last_name.errors %}
                <div class="alert alert-danger alert-dismissible">{{ form.last_name.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="email" name="email" placeholder="Email" id="id_email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" />
              </div>
              {% if form.email.errors %}
                <div class="alert alert-danger alert-dismissible">{{ form.email.errors }}</div>
              {% endif %}
              <div class="form-group">
                <input class="input" type="text" name="phone_number" placeholder="Telephone" id="id_phone_number" value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}" />
              </div>
              {% if form.phone_number.errors %}
                <div class="alert alert-danger alert-dismissible">{{ form.phone_number.errors }}</div>
              {% endif %}

              <div class="form-group">
                <label for="delivery" class="form-label">Delivery method:</label>
                <div style="display: inline-block; margin-left: 10px; margin-right: 10px;">
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="requires_delivery" id="id_requires_delivery_1" value="1" checked />
                    <label class="form-check-label" for="id_requires_delivery_1">Need delivery</label>
                  </div>
                </div>
                <div style="display: inline-block;">
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="requires_delivery" id="id_requires_delivery_0" value="0" />
                    <label class="form-check-label" for="id_requires_delivery_0">Pickup</label>
                  </div>
                </div>
              </div>

              <div class="form-group" id="deliveryAddressField">
                <label for="id_delivery_address">Delivery address:</label>
                <textarea class="input" type="text" name="delivery_address" placeholder="Address" id="id_delivery_address"></textarea>
              </div>
              {% if form.delivery_address.errors %}
                <div class="alert alert-danger alert-dismissible">{{ form.delivery_address.errors }}</div>
              {% endif %}

              <div class="form-group">
                <label class="form-label">Payment method:</label>
                <div style="display: inline-block; margin-right:10px; margin-left: 10px;">
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="payment_on_get" id="id_payment_on_get_0" value="0" checked />
                    <label class="form-check-label" for="id_payment_on_get_0">Card</label>
                  </div>
                </div>
                <div style="display: inline-block;">
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="payment_on_get" id="id_payment_on_get_1" value="1" />
                    <label class="form-check-label" for="id_payment_on_get_1">Cash/card upon receipt</label>
                  </div>
                </div>
              </div>
            </div>
            <!-- /Shipping Details -->

            <!-- Order notes -->
            <div class="order-notes">
              <textarea class="input" name="order_notes" placeholder="Order Notes" id="id_order_notes" value="{% if form.order_notes.value %}{{ form.order_notes.value }}{% endif %}"></textarea>
            </div>
            <br />
            <button type="submit" class="primary-btn order-submit">Create order</button>
            <!-- /Order notes -->
          </div>
        </form>

        <!-- Order Details -->
        <div class="col-md-5 order-details">
          <div class="section-title text-center">
            <h3 class="title">Your Order</h3>
          </div>

          {% include 'carts/includes/included_cart.html' %}
        </div>

        <!-- /Order Details -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->

  <script>
    $(function () {
      // Обработчик события радиокнопки выбора способа доставки
      $("input[name='requires_delivery']").change(function () {
        var selectedValue = $(this).val()
        // Скрываем или отображаем input ввода адреса доставки
        if (selectedValue === '1') {
          $('#deliveryAddressField').show()
        } else {
          $('#deliveryAddressField').hide()
        }
      })
    })
  </script>
{% endblock %}