electrostore/carts/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("cart_add/<slug:product_slug>", views.cart_add, name="cart_add"),
    path("cart_change/<int:cart_id>", views.cart_change, name="cart_change"),
    path("cart_remove/<int:cart_id>", views.cart_remove, name="cart_remove"),
]

electrostore/electrostore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("goods/", include("goods.urls", namespace="goods")),
    path("users/", include("users.urls", namespace="users")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electrostore/goods/urls.py
from django.urls import path
from . import views

app_name = "goods"

urlpatterns = [
    path("search", views.catalog, name="search"),
    path("<slug:product_slug>/", views.product, name="product"),
    path("catalog/<slug:category_slug>/", views.catalog, name="catalog"),
]

electrostore/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

electrostore/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

electrostore/goods/models.py
from django.db import models

# Create your models here.

electrostore/goods/forms.py
from django import forms

from main.models import Review


class ReviewForm(forms):
    body = forms.CharField()

    class Meta:
        model = Review()
        fields = ["body"]

electrostore/goods/views.py
from django.shortcuts import redirect, render
from main.models import Product, Category, Review, Rating
from django.db.models import Avg, F, ExpressionWrapper, DecimalField
from django.core.paginator import Paginator
from goods.utils import q_search


def catalog(request, category_slug=None):
    page = request.GET.get("page", 1)
    query = request.GET.get("q", None)
    sort_option = request.GET.get("sort", None)

    if category_slug == "all":
        goods = Product.objects.all()
    elif query:
        goods = q_search(query)
    else:
        goods = Product.objects.filter(category__slug=category_slug)

    if sort_option == "0":  # Popular
        goods = goods.annotate(average_rating=Avg("ratings__value")).order_by(
            "-average_rating"
        )
    elif sort_option == "1":  # Price: Low to High
        goods = goods.annotate(
            sell_price=ExpressionWrapper(
                F("price") - F("price") * F("discount") / 100,
                output_field=DecimalField(max_digits=7, decimal_places=2),
            )
        ).order_by("sell_price")
    elif sort_option == "2":  # Price: High to Low
        goods = goods.annotate(
            sell_price=ExpressionWrapper(
                F("price") - F("price") * F("discount") / 100,
                output_field=DecimalField(max_digits=7, decimal_places=2),
            )
        ).order_by("-sell_price")
    elif sort_option == "3":  # Discount
        goods = goods.filter(discount__gt=0)

    categories = Category.objects.all()
    top_sellings = (
        Product.objects.all()
        .annotate(average_rating=Avg("ratings__value"))
        .order_by("-average_rating")[:3]
    )
    total_count = Product.objects.count()

    paginator = Paginator(goods, 6)
    current_page = paginator.page(int(page))

    context = {
        "title": "Catalog",
        "goods": current_page,
        "categories": categories,
        "top_sellings": top_sellings,
        "total_count": total_count,
        "slug_url": category_slug,
    }
    return render(request, "goods/catalog.html", context)


def product(request, product_slug):
    # Pagination
    page = request.GET.get('page', 1)

    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    related_products = Product.objects.filter(category=product.category)
    reviews = Review.objects.filter(product=product.id)

    if request.method == "POST":
        if request.POST.get("rating"):
            rating_value = int(request.POST.get("rating"))
            rating, created = Rating.objects.get_or_create(
                user=request.user, product=product, defaults={'value': rating_value}
            )
            if not created:
                rating.value = rating_value
                rating.save()
        else:
            rating = None
        
        review = Review.objects.create(
            user=request.user, product=product, body=request.POST.get("body"), rating=rating
        )

        return redirect(request.META["HTTP_REFERER"])
    
    paginator = Paginator(reviews, 3)
    current_page = paginator.page(int(page))
    

    context = {
        "title": product.name,
        "product": product,
        "categories": categories,
        "related_products": related_products,
        "reviews": current_page,
        "count_reviews": reviews.count()
    }

    return render(request, "goods/product.html", context)

electrostore/goods/templates/goods/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load goods_tags %}

{% block content %}
  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- ASIDE -->
        <div id="aside" class="col-md-3">
          <!-- aside Widget -->
          <div class="aside">
            <h3 class="aside-title">Categories</h3>
            <div class="checkbox-filter">
              <div class="input-checkbox">
                <a href="{% url 'goods:catalog' 'all' %}">
                  <span></span>
                  ALL
                  <small>({{ total_count }})</small>
                </a>
              </div>
              {% for category in categories %}
                <div class="input-checkbox">
                  <a href="{% url 'goods:catalog' category.slug %}">
                    <span></span>
                    {{ category.name }}
                    <small>({{ category.product_count }})</small>
                  </a>
                </div>
              {% endfor %}
            </div>
          </div>
          <!-- /aside Widget -->
          <br /><br />
          <!-- aside Widget -->
          <div class="aside">
            <h3 class="aside-title">Top selling</h3>
            {% for product in top_sellings %}
              <div class="product-widget">
                <div class="product-img">
                  <img src="{{ product.images.first.image.url }}" alt="{{ product.name }}" />
                </div>
                <div class="product-body">
                  <p class="product-category">{{ product.category.name }}</p>
                  <h3 class="product-name"><a href="{% url 'goods:product' product.slug %}">{{ product.name }}</a></h3>
                  <h4 class="product-price">
                    ${{ product.sell_price|add_spaces }} {% if product.discount %}
                      <del class="product-old-price">${{ product.price|add_spaces }}</del>
                    {% endif %}
                  </h4>
                </div>
              </div>
            {% endfor %}
          </div>
          <!-- /aside Widget -->
        </div>
        <!-- /ASIDE -->

        <!-- STORE -->
        <div id="store" class="col-md-9">
          <!-- store top filter -->
          <form action="{% if request.get.q %}
                        {% url 'goods:search' %}
                      {% else %}
                        {% url 'goods:catalog' slug_url %}
                      {% endif %}"
                method="get">
            <div class="store-filter clearfix">
              <div class="store-sort">
                {% if request.get.q %}
                <input type="hidden" name="q" value="{{ request.get.q }}">
                {% endif %}
                <label>
                  Sort By:
                  <select class="input-select" name="sort" onchange="this.form.submit()">
                    <option value="0" {% if current_sort == '0' %}selected{% endif %}>Popular</option>
                    <option value="1" {% if current_sort == '1' %}selected{% endif %}>Price: Low to High</option>
                    <option value="2" {% if current_sort == '2' %}selected{% endif %}>Price: High to Low</option>
                    <option value="3" {% if current_sort == '3' %}selected{% endif %}>Discount</option>
                  </select>
                </label>
              </div>
            </div>
          </form>
          <!-- /store top filter -->



          <!-- store products -->
          <div class="row">
            {% for product in goods %}
              <!-- product -->
              <div class="col-md-4 col-xs-6">
                <div class="product">
                  <div class="product-img">
                    <img src="{{ product.images.first.image.url }}" alt="{{ product.name }}" />
                    <div class="product-label">
                      {% if product.discount %}
                        <span class="sale">-{{ product.discount|floatformat:0 }}%</span>
                      {% endif %}
                    </div>
                  </div>
                  <div class="product-body">
                    <p class="product-category">{{ product.category.name }}</p>
                    <h3 class="product-name"><a href="{% url 'goods:product' product.slug %}">{{ product.name }}</a></h3>
                    <h4 class="product-price">
                      ${{ product.sell_price|add_spaces }} {% if product.discount %}
                        <del class="product-old-price">${{ product.price|add_spaces }}</del>
                      {% endif %}
                    </h4>
                    <div class="product-rating">
                      {% for i in '12345' %}
                        {% if forloop.counter <= product.average_rating %}
                          <i class="fa fa-star"></i>
                        {% else %}
                          <i class="fa fa-star-o"></i>
                        {% endif %}
                      {% endfor %}
                    </div>
                  </div>
                  <div class="add-to-cart">
                    <a href="{% url "cart:cart_add" product.slug %}">
                    <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                  </a>
                  </div>
                </div>
              </div>
              <!-- /product -->
            {% endfor %}
          </div>
          <!-- /store products -->

          <!-- store bottom filter -->
          {% if goods %}
            <div class="store-filter clearfix">
              <ul class="store-pagination">
                {% if goods.has_previous %}
                  <li>
                    <a href="?{% change_params page=goods.previous_page_number %}"><i class="fa fa-angle-left"></i></a>
                  </li>
                {% endif %}
                {% for page in goods.paginator.page_range %}
                  {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %}
                    <li class="{% if goods.number == page %}active{% endif %}">
                      <a href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                {% if goods.has_next %}
                  <li>
                    <a href="?{% change_params page=goods.next_page_number %}"><i class="fa fa-angle-right"></i></a>
                  </li>
                {% endif %}
              </ul>
            </div>
          {% endif %}
          <!-- /store bottom filter -->

        </div>
        <!-- /STORE -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->
{% endblock %}

electrostore/goods/templates/goods/product.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
  <!-- BREADCRUMB -->
  <div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-12">
          <ul class="breadcrumb-tree">
            <li>
              <a href="{% url 'main:index' %}">Home</a>
            </li>
            <li>
              <a href="#">All Categories</a>
            </li>
            <li>
              <a href="#">{{ product.category.name }}</a>
            </li>
            <li class="active">{{ product.name }}</li>
          </ul>
        </div>
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /BREADCRUMB -->

  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- Product main img -->
        <div class="col-md-5 col-md-push-2">
          <div id="product-main-img">
            {% for image in product.images.all %}
              <div class="product-preview">
                <img src="{{ image.image.url }}" alt="{{ product.name }}" />
              </div>
            {% endfor %}
          </div>
        </div>
        <!-- /Product main img -->

        <!-- Product thumb imgs -->
        <div class="col-md-2 col-md-pull-5">
          <div id="product-imgs">
            {% for image in product.images.all %}
              <div class="product-preview">
                <img src="{{ image.image.url }}" alt="{{ product.name }}" />
              </div>
            {% endfor %}
          </div>
        </div>
        <!-- /Product thumb imgs -->

        <!-- Product details -->
        <div class="col-md-5">
          <div class="product-details">
            <h2 class="product-name">{{ product.name }}</h2>
            <div>
              <div class="product-rating">
                {% for i in '12345' %}
                  {% if forloop.counter <= product.average_rating %}
                    <i class="fa fa-star"></i>
                  {% else %}
                    <i class="fa fa-star-o"></i>
                  {% endif %}
                {% endfor %}
              </div>
              <a class="review-link" href="#">10 Review(s) | Add your review</a>
            </div>
            <div>
              <h3 class="product-price">
                ${{ product.sell_price|add_spaces }} {% if product.discount %}
                  <del class="product-old-price">${{ product.price|add_spaces }}</del>
                {% endif %}
              </h3>
              <span class="product-available">
                {% if product.quantity > 0 %}
                  In Stock
                {% else %}
                  Endeded
                {% endif %}
              </span>
            </div>
            <p>{{ product.little_description }}</p>
            <br />

            <form method="post" action="{% url 'cart:cart_add' product.slug %}">
              {% csrf_token %}
              <div class="add-to-cart">
                <div class="qty-label">
                  Qty<div class="input-number">
                    <input type="number" name="quantity" class="qty" min="1" />
                  </div>
                </div>
                <a href="{% url 'cart:cart_add' product.slug %}"><button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button></a>
              </div>
            </form>

            <ul class="product-links">
              <li>Category:</li>
              <li>
                <a href="#">{{ product.category.name }}</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /Product details -->

        <!-- Product tab -->
        <div class="col-md-12">
          <div id="product-tab">
            <!-- product tab nav -->
            <ul class="tab-nav">
              <li class="active">
                <a data-toggle="tab" href="#tab1">Description</a>
              </li>
              <li>
                <a data-toggle="tab" href="#tab3">Reviews ({{count_reviews}})</a>
              </li>
            </ul>
            <!-- /product tab nav -->

            <!-- product tab content -->
            <div class="tab-content">
              <!-- tab1 -->
              <div id="tab1" class="tab-pane fade in active">
                <div class="row">
                  <div class="col-md-12">
                    <p>{{ product.description }}</p>
                  </div>
                </div>
              </div>
              <!-- /tab1 -->

              <!-- tab3 -->
              <div id="tab3" class="tab-pane fade in">
                <div class="row">
                  <!-- Rating -->
                  <div class="col-md-3">
                    <div id="rating">
                      <div class="rating-avg">
                        <span>{{ product.average_rating }}</span>
                        <div class="rating-stars">
                          {% for i in '12345' %}
                            {% if forloop.counter <= product.average_rating %}
                              <i class="fa fa-star"></i>
                            {% else %}
                              <i class="fa fa-star-o"></i>
                            {% endif %}
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /Rating -->
                  
                  <!-- Reviews -->
                  <div class="col-md-6">
                    <div id="reviews">
                      <ul class="reviews">
                        {% for review in reviews %}
                        <li>
                          <div class="review-heading">
                            <h5 class="name">{{review.user.username}}</h5>
                            <p class="date">{{review.created}}</p>
                            <div class="review-rating">
                              {% for i in '12345' %}
                              {% if forloop.counter <= review.rating.value %}
                                <i class="fa fa-star"></i>
                              {% else %}
                                <i class="fa fa-star-o"></i>
                              {% endif %}
                            {% endfor %}
                            </div>
                          </div>
                          <div class="review-body">
                            <p>{{review.body}}</p>
                          </div>
                        </li>
                        {% endfor %}
                      </ul>
                      {% if reviews %}
                      <ul class="reviews-pagination">
                        <li class="{% if not reviews.has_previous %}disabled{% endif %}">
                          <a href="{% if reviews.has_previous %}?{% change_params page=reviews.previous_page_number %}{% else %}#{% endif %}">
                          <i class="fa fa-angle-left"></i>
                          </a>
                        </li>

                        {% for page in reviews.paginator.page_range%}
                        {% if page >= reviews.number|add:-2 and page <= reviews.number|add:2 %}
                        <li class="{% if reviews.number == page%} active {% endif %}">
                          <a href="?{% change_params page=page %}">{{page}}</a>
                        </li>
                        {% endif %}
                        {% endfor %}

                        <li class="{% if not reviews.has_next %}disabled{% endif %}">
                          <a href="{% if reviews.has_next %}?{% change_params page=reviews.next_page_number %}{% else %}#{% endif %}">
                          <i class="fa fa-angle-right"></i>
                          </a>
                        </li>
                      </ul>
                      {% endif %}
                    </div>
                  </div>
                  <!-- /Reviews -->

                  <!-- Review Form -->
                  <div class="col-md-3">
                    <div id="review-form">
                      {% if user.is_authenticated %}
                      <form class="review-form" action="{% url 'goods:product' product.slug %}" method="POST">
                        {% csrf_token %}
                        <textarea class="input" placeholder="Your Review" id="id_body" name="body"></textarea>
                        <div class="input-rating">
                          <span>Your Rating:</span>
                          <div class="stars">
                            <input id="star5" name="rating" value="5" type="radio" /><label for="star5"></label>
                            <input id="star4" name="rating" value="4" type="radio" /><label for="star4"></label>
                            <input id="star3" name="rating" value="3" type="radio" /><label for="star3"></label>
                            <input id="star2" name="rating" value="2" type="radio" /><label for="star2"></label>
                            <input id="star1" name="rating" value="1" type="radio" /><label for="star1"></label>
                          </div>
                        </div>
                        <button class="primary-btn">Submit</button>
                      </form>
                      {% else %}
                      Log in for writing review - 
                      <a href="{% url "users:login" %}">LOGIN</a>
                      {% endif %}
                    </div>
                  </div>
                  <!-- /Review Form -->
                </div>
              </div>
              <!-- /tab3 -->
            </div>
            <!-- /product tab content -->
          </div>
        </div>
        <!-- /product tab -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->

  <!-- Section -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-12">
          <div class="section-title text-center">
            <h3 class="title">Related Products</h3>
          </div>
        </div>

        {% for product in related_products %}
          <!-- product -->
          <div class="col-md-3 col-xs-6">
            <div class="product">
              <div class="product-img">
                <img src="{{ product.images.first.image.url }}" alt="{{ product.name }}" />
                {% if product.discount %}
                  <div class="product-label">
                    <span class="sale">-{{ product.discount|floatformat:0 }}%</span>
                  </div>
                {% endif %}
              </div>
              <div class="product-body">
                <p class="product-category">{{ product.category }}</p>
                <h3 class="product-name"><a href="{% url 'goods:product' product.slug %}">{{ product.name }}</a></h3>
                <h4 class="product-price">
                  ${{ product.sell_price|add_spaces }} {% if product.discount %}
                    <del class="product-old-price">${{ product.price|add_spaces }}</del>
                  {% endif %}
                </h4>
              </div>
              <a class="add-to-cart" href="{% url 'cart:cart_add' product.slug %}"><button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button></a>
            </div>
          </div>
          <!-- /product -->
        {% endfor %}
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /Section -->
{% endblock %}